version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  # frontend:
  #  build:
  #   context: ./frontend
  # ports:
  #  - "5173:5173"
  #  depends_on:
  #   - backend
