spring:
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: devstral-small-latest

  datasource:
    url: jdbc:postgresql://db-postgresql-fra1-85342-do-user-24244176-0.l.db.ondigitalocean.com:25060/defaultdb
    username: tim2
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true