spring:
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: devstral-small-latest
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never

  datasource:
    url: jdbc:postgresql://db-postgresql-fra1-85342-do-user-24244176-0.l.db.ondigitalocean.com:25060/defaultdb
    username: tim2
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: klupica

db:
  schema:
    name: klupica

ai:
  prompt:
    md:
      name: prompt

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG